title: TEST Minimal theme
logo: /MedCom_logo_2015.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
layout: page
permalink: https://github.com/tmsMedcom/GitHubPagesTest/blob/2182e4351e814791f8c258502ec22f342fcc58cc/GitHubPages.md
