id: dk.fhir.ig.dk-medcom-hospitalnotification
canonical: http://medcomfhir.dk/fhir/hospitalnotification
name: MedComHospitalNotification
title: "DK MedCom HospitalNotification"
description: The DK MedCom HospitalNotification IG
status: active
version: "2.0.0"
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Build CI
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core:
   uri: https://hl7.dk/fhir/core/1.1.0/
   version: 1.1.0
  dk.fhir.ig.dk-medcom-core: current
  dk.fhir.ig.dk-medcom-messaging: current

menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifacts: artifacts.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-juristiction: true
  apply-publisher: true
