@startuml HNAdmitFinish

'layout
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
  }
hide circle
hide empty members
skinparam SameClassWidth true
skinparam Ranksep 10


'title
title Simplified example: Admit and finish inpatient

'Message 1: Admit inpatient
package "Message 1: Admit inpatient" as admit <<Frame>> #LightBlue{
    class "Bundle 1 (MedComHospitalNotificationMessage)" as admitB #LightBlue{
        id = BUN1
        type = "message"
        timestamp = 2021-12-01T12:00:10+02:00
    }
    class "MessageHeader 1 (MedComHospitalNotificationMessageHeader)" as admitMH #LightBlue{
        id = MH1
        event = "hospital-notification-message"
        destination:primary = MedComMessagingOrganization/RO1
        destination:primary.use = "primary"
        destination:primary.endpoint = *url to receiver of HospitalNotification message*
        sender = MedComMessagingOrganization/SO1
        source.url = *url to receiver of Acknowledgement*
        focus = MedComHospitalNotificationEncounter/ENC1
    }
    class "Reciver Organization 1 (MedComMessagingOrganization)" as admitROrg #LightGoldenRodYellow{
        id = RO1
        eanIdentifier = 987654321
        sorIdentifier = 741852963
    }
    class "Sender Organization 1 (MedComMessagingOrganization)" as admitSOrg #LightGoldenRodYellow{
        id = SO1
        eanIdentifier = 123456789
        sorIdentifier = 369258147
    }
    class "Encounter 1 (MedComHospitalNotificationEncounter)" as admitENC #LightBlue{
        id = ENC1
        status = "in-progress"
        class = "IMP"
        subject = MedComCorePatient/PA1
        episodeOfCare = *refence to the episode of care*
        period.start = 2021-12-01T12:00:00+02:00
        serviceProvider = MedComCoreOrganization/SPO1
    }
    class "Patient 1 (MedComCorePatient)" as admitPT #LightCoral{
        id = PA1
        cprIdentifier = 030201-9292
        name.family = Flame
        name.given = Eric
    }
    class "ServiceProvider Organization 1 (MedComCoreOrganization)" as admitSPOrg #LightCoral{
        id = SPO1
        sorIdentifier = 369258147
    }
    class "Provenance 1 (MedComMessagingProvenance)" as admitPRO #LightGoldenRodYellow{
        id = PROV2
        target = MH1
        occuredDateTime = 2021-12-01T12:00:10+02:00
        recorded = 2021-12-01T12:00:20
        activity = "admit-inpatient"
        agent.who = MedComMessagingOrganization/SO1
    }

admitB -[hidden]- admitMH
admitMH -[hidden]- admitROrg
admitROrg-[hidden]-admitSOrg
admitSOrg-[hidden]-admitENC
admitENC-[hidden]-admitPT
admitPT-[hidden]-admitSPOrg
admitSPOrg-[hidden]-admitPRO
}

'Message 2: Finished inpatient
package "Message 2: Finished inpatient" as finished <<Frame>> #LightBlue{
    class "Bundle 2 (MedComHospitalNotificationMessage)" as finishedB #LightBlue{
        id = BUN2
        type = "message"
        timestamp = 2021-12-03T14:00:10+02:00
    }
    class "MessageHeader 2 (MedComHospitalNotificationMessageHeader)" as finishedMH #LightBlue{
        id = MHID2
        event = "hospital-notification-message"
        destination:primary = MedComMessagingOrganization/RO2
        destination:primary.use = "primary"
        destination:primary.endpoint = *url to receiver of HospitalNotification message*
        sender = MedComMessagingOrganization/SO1
        source.url = *url to receiver of Acknowledgement*
        focus = MedComHospitalNotificationEncounter/ENC2
    }
    class "Reciver Organization 1 (MedComMessagingOrganization)" as finishedROrg #LightGoldenRodYellow{
        id = RO1
        eanIdentifier = 987654321
        sorIdentifier = 741852963
    }
    class "Sender Organization 1 (MedComMessagingOrganization)" as finishedSOrg #LightGoldenRodYellow{
        id = SO1
        eanIdentifier = 123456789
        sorIdentifier = 369258147
    }
    class "Encounter 2 (MedComHospitalNotificationEncounter)" as finishedENC #LightBlue{
        id = ENC2
        status = "finished"
        class = "IMP"
        subject = MedComCorePatient/PA1
        episodeOfCare = *refence to the episode of care*
        period.start = 2021-12-01T12:00:00+02:00
        serviceProvider = MedComCoreOrganization/SPO1
    }
    class "Patient 1 (MedComCorePatient)" as finishedPT #LightCoral{
        id = PA1
        cprIdentifier = 030201-9292
        name.family = Flame
        name.given = Eric
    }
    class "ServiceProvider Organization 1 (MedComCoreOrganization)" as finishedSPOrg #LightCoral{
        id = SPO1 
        sorIdentifier = 369258147
    }    
    class "Provenance 1 (MedComMessagingProvenance)" as admitfinishedPRO #LightGoldenRodYellow{
        id = PROV1
        target = MH1
        occuredDateTime = 2021-12-01T12:00:10+02:00
        recorded = 2021-12-01T12:00:20
        activity = "admit-inpatient"
        agent.who = MedComMessagingOrganization/SO1
    }
    class "Provenance 2 (MedComMessagingProvenance)" as finishedPRO #LightGoldenRodYellow{
        id = PROV2        
        target = MH2
        occuredDateTime = 2021-12-01T12:00:10+02:00
        recorded = 2021-12-01T12:00:20
        activity = "admit-inpatient"
        agent.who = MedComMessagingOrganization/SO1
        entity.role = "deriviation"
        entity.what = MessageHeader/MH1
    }
finishedB-[hidden]-finishedMH
finishedMH-[hidden]-finishedROrg
finishedROrg-[hidden]-finishedSOrg
finishedSOrg-[hidden]-finishedENC
finishedENC-[hidden]-finishedPT
finishedPT-[hidden]-finishedSPOrg
finishedSPOrg-[hidden]-admitfinishedPRO
admitfinishedPRO-[hidden]-finishedPRO

}

' pile mellem de to beskeder
' admit --> finished


@enduml

