title: "MedCom Hospital Notification in FHIR"
description: "This page includes content about HospitalNotification (DA: Sygehusadvis)"
logo: Medcom-logo-2015.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal