title: TEST Minimal theme
logo: https://github.com/tmsMedcom/GitHubPagesTest/blob/0ea219764dccdbdd5d53e18e46663f81bcb9e1a3/docs/Medcom_logo_2015.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
