title: MedCom Hospital Notification in FHIR
description: This page includes content about HospitalNotification (DA: Sygehusadvis)
logo: https://github.com/tmsMedcom/GitHubPagesTest/blob/0ea219764dccdbdd5d53e18e46663f81bcb9e1a3/docs/Medcom_logo_2015.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
date:
  type: "date"
  options:
    format: "iso8601" # "iso8601" (default), "timestamp-seconds"
author: 
  name: MedCom
  email: fhir@medcom.dk
  github: https://github.com/hl7dk
# Reasing files
include: 
  - index.md
  - contact.md
